outdir = "nearextremal"

nx = 64
ny = 32
nt = 80000
ts = 50  # save every ts time steps

psi_spin    = -2 # spin-weight of linear evolution scalar
psi_falloff = -1 # falloff (in r) of linear evolution scalar

m_vals = [-2,2]

id_kind = "gaussian"

id_l_ang = [2,2]
id_ru = [6.0,6.0]
id_rl = [1.5,1.5] 
id_width = [10.0,10.0]
id_amp = [
	[0.2,0.0],
	[0.2,0.0]
]  
# format: [real part, imaginary part]

cl  = 1.0 # compactification scale
cfl = 0.5 # CFL number
bhs = 0.999 # black hole spin 
bhm = 1.0 # black hole mass
